theme: jekyll-theme-cayman
title: Hateful Memes Detection
description: Using multiple types of annotation extracted from hateful-memes dataset and feed those data into multi-modal transformers to achieve high accuracy.
